### ISSUE TITLE
android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by Kelvao** [zhkrb/cloudflare-scrape-Android#1]
android.os.NetworkOnMainThreadException

**Comment by johnchrisdc** [comment]
Use AsyncTask

**Comment by Kelvao** [comment]
how can i use?

**Comment by Kelvao** [comment]
doesn't work

**Comment by johnchrisdc** [comment]
You still got android.os.NetworkOnMainThreadException?

You can use this as reference

https://github.com/johnchrisdc/Nasira-Ba-/blob/e389040f0cf6b36ce97ac28e90b89409e32ba718/app/src/main/java/xyz/jcdc/nasiraba/MainActivity.java#L119

**Comment by zhkrb** [comment]
You need use code in other Thread. Such as: new Thead()...

**Comment by zhkrb** [comment]
@Kelvao You need use code in other Thread, such as new Thread()....

**Comment by Kelvao** [comment]
works perfect! thank you 😄
