### ISSUE TITLE
E/cloudflare: Get Cookie Failed when try to access https://zooqle.prox4you.xyz/

### ISSUE THREAD

**Issue by NSBlackMirror** [zhkrb/cloudflare-scrape-Android#10]
String url = "https://zooqle.prox4you.xyz/";
        String UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36";
            Cloudflare cf = new Cloudflare(url);
            cf.setUser_agent(UA);
            cf.getCookies(new Cloudflare.cfCallback() {
                @Override
                public void onSuccess(List<HttpCookie> cookieList) {

                    

                  String ok = "";
                }

                @Override
                public void onFail() {

                    String okay = "";
                }
            });

Every time i am receiving onFail callback...Error msg i am receiving is "Cloudflare: Get Cookie Failed"

Clouldfalir bypass was working for this website now its not accessible anymore

**Comment by zhkrb** [comment]
It can pass now.
I don't know why sometimes it can't pass, it need more tests to determine the problem

**Comment by NSBlackMirror** [comment]
its working sometimes and sometimes its not..

**Comment by tmxd09887** [comment]
after some test,some time not work
