### ISSUE TITLE
Request for help to get a picture ?

### ISSUE THREAD

**Issue by kamarad98** [zhkrb/cloudflare-scrape-Android#13]
First of all, thank you very much for your work. I'm a beginner in computer science. Could you show me an example of use with Picasso or Glide to retrieve an image on a site ? I don't know how to use Cloudflare cookies to use with these libraries. Have you ever managed to do it ? Thank you.

**Comment by zhkrb** [comment]
```
public static void displayWithCookie(String url, ImageView imageView, String cookie) {
       GlideUrl glideUrl = new GlideUrl(url,new LazyHeaders.Builder()
                                    .addHeader("Cookie",cookie)
                                    .build());
       sManager.load(glideUrl ).apply(options).into(imageView);    
}
```
The `sManager` is Glide requestManager, you can use `Cloudflare.listToString()` to conversion List to String

**Comment by kamarad98** [comment]
@zhkrb  Thanks. But I have a problem and I can't find any solution. 

I have this error :
`W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored`

And after I have this : 
`W/Glide: Load failed for "PICTURELINK" with size [200x250]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException("PICTURELINK")
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException("PICTURELINK")
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException("PICTURELINK")
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: "PICTURELINK"`

**Comment by kamarad98** [comment]
I have this in my gradle : 
`implementation 'com.github.bumptech.glide:glide:4.9.0'
 annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'`

**Comment by zhkrb** [comment]
It look's like you passed in a string "PICTURELINK" , not picture url

**Comment by kamarad98** [comment]
No, I just hid the link. It's a link to an picture (I'm able to open the link on my browser and see the image).

**Comment by kamarad98** [comment]
I can recover pictures when the website doesn't have a "cloudflare". But if the website have it, I have the error...

**Comment by zhkrb** [comment]
Could you post your code, or pic url? It will make us easy to check it

**Comment by kamarad98** [comment]
This is my code to get the picture : 
`public class GalleryAdapter extends BaseAdapter {

    private List<Book> listforview;
    private LayoutInflater inflator;
    private RequestManager sManager;

    public GalleryAdapter(Context con, List<Book> list, RequestManager sManager)
    {
        super();
        listforview=list;
        inflator=LayoutInflater.from(con);
        this.sManager = sManager;
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public int getCount() {
        return listforview.size();
    }

    @Override
    public Object getItem(int position) {
        return listforview.get(position);
    }

    private class ViewHolder
    {
        TextView title;
        ImageView image;
        TextView info;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View v = convertView;
        final ViewHolder vholder;
        if(convertView==null)
        {
            v =inflator.inflate(R.layout.gridview_Book_element,null);

            vholder =new ViewHolder();
            vholder.title=(TextView) v.findViewById(R.id.adaptertitre);
            vholder.info =(TextView) v.findViewById(R.id.adapterInfo);
            vholder.image =(ImageView) v.findViewById(R.id.adapterimage);

            v.setTag(vholder);
        }
        else{
            vholder =(ViewHolder) v.getTag();
        }

        final Book item = listforview.get(position);

        RequestOptions requestOptions = new RequestOptions();
        requestOptions=requestOptions.placeholder(R.drawable.logo_placeholder);

        GlideUrl glideUrl = new GlideUrl(item.getUrlPhoto(),new LazyHeaders.Builder()
                .addHeader("Cookie",item.getCloudflare())
                .build());
        sManager.load(glideUrl).apply(requestOptions).into(vholder.image);
        
        vholder.title.setText(item.getTitle());
        vholder.info.setText(item.getInformation());
        return v;
    }
}
`

**Comment by zhkrb** [comment]
```GlideUrl glideUrl = new GlideUrl(item.getUrlPhoto(),new LazyHeaders.Builder()
            .addHeader("Cookie",item.getCloudflare())
            .addHeader("User-Agent",ua)
            .build());
```
try this, make sure `ua` is as same as you get Cloudflare cookie's ua

**Comment by kamarad98** [comment]
Thanks. It solved my problem !
