### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by destroyxx** [zhkrb/cloudflare-scrape-Android#14]
Hello, can you update the library please ?  thank you

**Comment by zhkrb** [comment]
Ok, I will update within 1 day, but if there are new changes, I can only wait until the end of December, because I am too busy.

**Comment by destroyxx** [comment]
Ok, no problem. Thx.

**Comment by zhkrb** [comment]
Now it's works fine on my phone, try it

**Comment by destroyxx** [comment]
Thanks for the update. I have an error : https://i.imgur.com/YgQbejv.png

**Comment by zhkrb** [comment]
emmm, I forgot to check for null. Now updated
