### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Doomsdayrs** [zhkrb/cloudflare-scrape-Android#15]
Will you add a license?

**Comment by zhkrb** [comment]
no

**Comment by Doomsdayrs** [comment]
Is this application considered open source?

**Comment by zhkrb** [comment]
of cause，In my opinion this is a very simple project, so I don't add any licenses to limit it.

**Comment by zhkrb** [comment]
of cause，In my opinion this is a very simple project, so I don't add any licenses to limit it.

**Comment by Doomsdayrs** [comment]
MIT License is a 'do what you wish' type license, No limitations at all

**Comment by zhkrb** [comment]
Ok, now it has been added
