### ISSUE TITLE
Not work always and for all site cloudflare protected

### ISSUE THREAD

**Issue by 0Franky** [zhkrb/cloudflare-scrape-Android#19]
Sometimes, for some sites, no cookies are returned. The method fails.
Does it happen because a longer validation is required (connection timeout)?
Test site: https://ilgeniodellostreaming.si/

In addition, the method fails on sites that do not (always) require cloudflare protection.
Ex:
https://www.animeworld.cc/ (here it works)
https://www.animeworld.cc/watch/sands-of-destruction.ebAhB (here not)

NB
It cannot retrieve the redirected url

**Comment by zhkrb** [comment]
i'm checking

**Comment by zhkrb** [comment]
1.site https://ilgeniodellostreaming.si/ it looks like there's something wrong with the url configuration, The redirect URL doesn't work sometime.

2.add 302 http code check, now it works fine in my test. Try to use new version `0.1.2`

**Comment by 0Franky** [comment]
Thanks, it works now for that, but has problems with challenge like:
__cf_chl_jschl_tk__   and   __cf_chl_captcha_tk__
I don't know if it can be solved.

**Comment by zhkrb** [comment]
Thank you, I'm checking

**Comment by 0Franky** [comment]
Example:
https://www.netfreex.pro/?s=elite 
=> 
https://www.netfreex.pro/?s=elite&__cf_chl_jschl_tk__=ea627d745eb31d55a14b06a6d1791d41a4bc0889-1586987086-0-AcgTyXs_FHnyCLF2rJnN6mccQ3dMnTWC5okiidZXLJoq8gC8gHbhbBrQ0a6xqg0FWZM4ijn_lrKphTvy22twk55yBpsi9LaNDk9TR-Sb-IYn6-KWLHY0fDZywhusx9Zo6pv5aUB0yvDB-cXRFH5VexHTOKoiMLy7WBz6U11gyvbVaYdgEGuYff7reEZtsCNrtsy2Xk-FmAhQs3X5e1GyOR3xCVJeUviSKv-FDD1LUFFMe1p7AL2owMH7kqisJHILk3Iz4lvk6twCnpkOlj49d3UxVZEPadzdSv8oNXwG9wxs
