### ISSUE TITLE
How to make it for desktop

### ISSUE THREAD

**Issue by lurumdare** [zhkrb/cloudflare-scrape-Android#20]
Android not needed.

**Comment by zhkrb** [comment]
You need rewrite some code. 

Network library depends `HttpURLConnection`, you can rewrite for Okhttp or httpClient. 

JS parser depends `v8` or `Rhino`, just copy one of the library to your project and depend it.

**Comment by lurumdare** [comment]
I'm like `jsoup`

**Comment by zhkrb** [comment]
emm...
I have no plans to rewrite code with jsoup.
But they realize in a similar way, get 503 response body and cookie, useing js parser to count js code, then request the url with cookie and answer, It will return visit cookie.

**Comment by lurumdare** [comment]
Okay
No problem 
Close
