### ISSUE TITLE
Get Cookie Failed

### ISSUE THREAD

**Issue by UnoThe** [zhkrb/cloudflare-scrape-Android#22]
Hi, i am getting cloudflare: Get Cookie Failed, i am using 
com.zhkrb.cloudflare-scrape-android:scrape-rhino:0.1.4
the code used to work before 
thank you.

**Comment by zhkrb** [comment]
Sorry to reply late, Can you provide the website url？

**Comment by Freddy12** [comment]
Try any URL.

They completely changed it now.

Here are few:
https://hqcrack.net
https://vorek.pl
https://www.heroturko.to

**Comment by jaysowen** [comment]
确实失效了，官方换了规则，请问还会更新吗？

**Comment by zhkrb** [comment]
This is a considerable update, I'm trying

**Comment by Freddy12** [comment]
Any news? :)

**Comment by zhkrb** [comment]
Reverse JS code becomes very difficult, maybe the only way get cookies is using WebView. But this is something I personally don't want to see

**Comment by zhkrb** [comment]
Sadly, only work on WebView branch. I will update it in a day.

**Comment by jaysowen** [comment]
> Sadly, only work on WebView branch. I will update it in a day.
Really appreciate it.

**Comment by zhkrb** [comment]
Branch it's  ready to update.
Try testing the website with this [release](https://github.com/zhkrb/cloudflare-scrape-Android/releases/tag/0.01)

If there are any questions or Suggestions, I will try to change it before update
But right now, I need to get some sleep

**Comment by Freddy12** [comment]
Are you sure the source code is correct in that release?

It looks 100% the same as the old (without any WebView and the same old regex'es which are not valid anymore).Į

**Comment by zhkrb** [comment]
emm, I uploaded a test APK to release that I hope you can test.

But no matter, I've found some problems

**Comment by Freddy12** [comment]
The source code zip and tar.gz are still old ones.

I'm not running on Android.

**Comment by zhkrb** [comment]
yup, I only uploaded APK before this.

now , all change is uploaded. copy `cloudflare_scrape_webview` module to your project or running Test demo.
If you find any problem ,please let me know. If it's all works fine, I will upload it to Jcenter and renew README
