### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by Cherrio-LLC** [zhkrb/cloudflare-scrape-Android#24]
I'm getting this error with https://www.thenetnaija.com/videos/series

**Comment by zhkrb** [comment]
'v8' and 'rhino' branch is discarded, please use 'webview' branch. I will update README as soon as i can

**Comment by Cherrio-LLC** [comment]
Is the demo apk up to date with the webview branch? Cuz I tested it and the progressbar keep loading

**Comment by zhkrb** [comment]
yup, and I find out this issues, it's fixing

**Comment by Cherrio-LLC** [comment]
Okay when your done fixing notify me. I implemented your logic and I got the cf_clearance cookie, but when I use it to request the main website, It still returns to cloudflare ddos page. Any ideas?

**Comment by zhkrb** [comment]
Use all cookies to visit, make sure set same `user-agent`

**Comment by Cherrio-LLC** [comment]
Thanks. I think the webview branch is the best.

**Comment by Cherrio-LLC** [comment]
I can confirm that it works 100%
