### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by congdanh1608** [zhkrb/cloudflare-scrape-Android#25]
Hi,
Thanks for your library.
I got issue: Failed to resolve: com.zhkrb.cloudflare-scrape-android:scrape-webview:0.0.2

I already added `  repositories {
        google()
        jcenter()
...
}` into build.gradle.

Do you have any idea? Thank you.

**Comment by zhkrb** [comment]
Sorry, I forget publish to Jcenter, now is updated

**Comment by congdanh1608** [comment]
Thank you.
