### ISSUE TITLE
Some help... 

### ISSUE THREAD

**Issue by midou221** [zhkrb/cloudflare-scrape-Android#27]
thank you for your great effort bro..
I know you are very busy But Can you help me for deal with this my project problem?
Is it possible use your project for dealing with a  okhhtp?? 
https://stackoverflow.com/questions/63301952/how-to-bypass-cloudflare-ddos-protection-and-parse-html

**Comment by zhkrb** [comment]
You means to make a Factory or Interceptor?

**Comment by midou221** [comment]
Yes.. I don't know how to do that
Could you give me an example?

**Comment by zhkrb** [comment]
I think this is not a good idea, the main function of Interceptor is to rewrite requests and rewrite responses. But `cf-scrape` need other requests to get visite cookie. So using interceptors is not feasible.
You can try to maintain a global cookie and judge 403 and 503 in the response. If they get a 403 or 503 response, immediately suspend all requests, use `cf-scrape`  to update the cookie, and then make the request again

**Comment by midou221** [comment]
Thank u very much 
this will help me a lot
