### ISSUE TITLE
implementation error

### ISSUE THREAD

**Issue by xqk666** [zhkrb/cloudflare-scrape-Android#29]
When adding dependency  implementation ' com.zhkrb.cloudflare -scrape- android:scrape-webview : 0.0.4 ' my android studio will have an error: 
**error: failed to resolve: Sketch WebView
Affected Modules: app**

What is the reason?

**Comment by zhkrb** [comment]
`scrape-webview` doesn't dependent Sketch WebView.
Could you post your `build.gradle` file?

**Comment by xqk666** [comment]
After I tried many times, it turns out that my Gradle version is too low.
Thank you for your reply

**Comment by haidrrrry** [comment]
Failed to resolve: com.zhkrb.cloudflare-scrape-android:scrape-webview:0.0.4
