### ISSUE TITLE
HTTP 503 Error

### ISSUE THREAD

**Issue by NandanDesai** [zhkrb/cloudflare-scrape-Android#4]
I am trying to use your library to bypass Cloudflare JavaScript challenge and trying to scrape https://yts.unblocked.app website using Jsoup. Your library is letting me have the Cookies. But, when I try to use the same cookies like `doc=Jsoup.connect(url).cookies(cookies).userAgent(userAgent).followRedirects(true).get();`
I am getting an HTTP 503 error. Any idea on how to solve this?

**Comment by zhkrb** [comment]
It's passed for my test. did you use `Cloudflare.List2Map(cookieList)`to conversion the `cookieList` in Success callback to jsoup needed Map

**Comment by NandanDesai** [comment]
Yes. I used `Cloudflare.List2Map(cookieList)` to convert List to Map and then passed the Map to Jsoup on Success callback.
Sorry for bothering you but, if you have time, can you try bypassing Cloudflare check on https://yts.unblocked.app website? Thanks.

**Comment by zhkrb** [comment]
I tested this website , it's passed. Use breakpoints to view the Callback list , it will have two items `__cfduid` and `cf_clearance` for normal.

**Comment by NandanDesai** [comment]
Yes. Even I get `__cfduid` and `cf_clearance`. And when I convert List to Map and then pass it to Jsoup, I get 503 error. That's the problem.

**Comment by zhkrb** [comment]
I tried it a few times, it is all passed. Could you post your code block? it will make us easy to check it

**Comment by NandanDesai** [comment]
CloudflareBypass cf = new CloudflareBypass("https://yts.unblocked.app");
        cf.setUser_agent(CloudflareBypass.userAgent);
        cf.getCookies(new CloudflareBypass.cfCallback() {
            @Override
            public void onSuccess(List<HttpCookie> cookieList) {
                System.out.println("Cookies: "+ CloudflareBypass.listToString(cookieList));
                Jsoup.connect(url).cookies(CloudflareBypass.List2Map(cookieList)).userAgent(userAgent).followRedirects(true).get(); //503 error here
                //further web scraping here
            }

            @Override
            public void onFail() {
                System.out.println("CloudflareBypass failed. Sorry!");
            }
        });

**503 error comes when I pass the cookies to Jsoup.**

**Comment by zhkrb** [comment]
Oh, I have reproduced this problem. When i set two different User-Agent, it gets a 503 response code. check your code in `CloudflareBypass.userAgent` and `userAgent` ,  make sure they are consistent. You should set the same User-Agent.

**Comment by NandanDesai** [comment]
Oh yeah! That was the problem. Now it works! Thanks! 
Also, I felt that Google's [V8](https://search.maven.org/search?q=g:com.eclipsesource.j2v8) library that you have used is a little heavy (it's 1.9 MB JAR file or 4.1 MB AAR file). So, I have replaced it with Mozilla's [Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Download_Rhino) engine which is quite lightweight (it's 1.3 MB). If you want I can send you a pull request. If you are OK with Google's V8, then no problem. Thanks anyways for your time!!

**Comment by zhkrb** [comment]
Of course, I will merge it into a new branch and indicate it in the readme
