### ISSUE TITLE
Not working with https://zooqle.unblocked.krd/ site

### ISSUE THREAD

**Issue by NSBlackMirror** [zhkrb/cloudflare-scrape-Android#6]
`Cloudflare cf = new Cloudflare("https://zooqle.unblocked.krd/");
            cf.setUser_agent("Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-18) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36");
            cf.getCookies(new Cloudflare.cfCallback() {
                @Override
                public void onSuccess(List<HttpCookie> cookieList) {
                  String ok = "";
                }

                @Override
                public void onFail() {

                    String okay = "";
                }
            });`

everytime i got  onFail callback

is anything wrong with my implementation?

**Comment by zhkrb** [comment]
It's looks like add a new value in check url , Fixed in the latest version

**Comment by NSBlackMirror** [comment]
Thanks a lot sir ..Its working Now
Do you have any idea how can i get past the CAPTCHA challenge on https://rarbgprx.org website..

Basically i want to parse rarbg website inside my android app but when i try to parse it using jsoup it works only for one or two time then after i constantly receive this type of CAPTCHA challenge ..and i dont have any idea how can i get past those CAPTCHA challenge and get the HTML document of rarbg.

if you have any idea how can i solve this?

Thanks Again

**Comment by zhkrb** [comment]
Sorry to reply to you for so long. I'm try to visit this website few times , but didn't get any CAPTCHA challenges. So I can't give you more support.  This issue will be closed, you can still reply here .

**Comment by zhkrb** [comment]
O, I got the CAPTCHA. It will return a CAPTCHA challenge page for response code 403.

So my suggestion is try to save the `__cfduid` cookie when you get the 403 response. If it's not null, open a webview with this cookie, then You can easily pass this verification. And next, they will set cookie with `cf_clearance` value, save it

Have to be aware of is your `user-agent` must be consistent. Normally it is accessible until these two cookies expired
