### ISSUE TITLE
Doesn't work most of the time since 2 days ago

### ISSUE THREAD

**Issue by Mandrakia** [zhkrb/cloudflare-scrape-Android#8]
Hi I've been using it successfully for the past couple of months, but since 2 days ago it stopped working on http://www.japscan.to/ 
I noticed an update so I updated it but it still only works like 1 out of 10 times.

When debugging all seems good except after posting the answer the 301 response doesn't contain the cf_clearance cookie just the usual _cfuid

**Comment by Mandrakia** [comment]
There was an issue with the toFixed, I fixed it but it still doesn't work all the time, I'm still investigating

**Comment by zhkrb** [comment]
Not in toFixed , i'm checking

**Comment by Mandrakia** [comment]
Found it ! 
The S query parameter needs to be Url Encoded.

Once I did it success rate went way up.

**Comment by zhkrb** [comment]
Yes that's the point. The pass and the s value has encoded.  Now it fixed in latest version.
And by the way , you  need visit website for https , it will throw `IOException: Cleartext HTTP traffic to xxx.x.xxx.xx not permitted` when running in Android P

**Comment by Mandrakia** [comment]
And another crash now. They changed the script, lots of eval and other stuff now.

**Comment by Freddy12** [comment]
They are using just atob which is basically decodes base64.

They are always the same:
atob("ZG9jdW1l") - docume
atob("aW5uZXJIVE1M") - innerHTML

**Comment by Mandrakia** [comment]
I'm trying to implement atob by doing some java callbacks

**Comment by Mandrakia** [comment]
var t='www.japscan.to';var k='test';var document = {}; document.getElementById = function(elem){ return {innerHTML :'+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(+!![])+(+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]))'};};var a=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+!![]+!![]+[])+(+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));;a*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(+[])+(+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]));;a+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]));;a*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(+!![]));;a*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]));;a+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));;a-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+[])+(+[])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]));;a*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/(+(+((!+[]+!![]+!![]+[])+(+[])+(!+[]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])))+(function(p){return eval((true+"")[0]+"."+([]["fill"]+"")[3]+(+(101))["to"+String["name"]](21)[1]+(false+"")[1]+(true+"")[1]+Function("return escape")()(("")["italics"]())[2]+(true+[]["fill"])[10]+(undefined+"")[2]+(true+"")[3]+(+[]+Array)[10]+(true+"")[0]+"("+p+")")}(+((!+[]+!![]+!![]+!![]+!![]+[])))));;a-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(+[]));;a+=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]));;a-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));;a-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));;a*=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((!+[]+!![]+!![]+!![]+!![]+[])+(!+[]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(+[]));;a-=+((!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![])+(+[])+(!+[]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]))/+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![])+(!+[]+!![]+!![])+(!+[]+!![]+!![]+!![]+!![]+!![])+(!+[]+!![]+!![])+(+[]));;


That's my script avec my modifications, it runs without issues in chrome and returns a double. In v8 it crashes due to some undefined method

**Comment by Freddy12** [comment]
It probably doesn't like something in this peace:

+(function(p){return eval((true+"")[0]+"."+([]["fill"]+"")[3]+(+(101))"to"+String["name"][1]+(false+"")[1]+(true+"")[1]+Function("return escape")()(("")"italics")[2]+(true+[]["fill"])[10]+(undefined+"")[2]+(true+"")[3]+(+[]+Array)[10]+(true+"")[0]+"("+p+")")}

It has "undefined" in the middle.

Maybe fill function acts differently in V8 then in browser?

**Comment by Mandrakia** [comment]
it encodes to t.charCodeAt(p) but I had to hardcode it because v8 was unable to get to that result. I don't know why.

**Comment by Mandrakia** [comment]
I get the code answer without a crash now, but it still doesn't work no clue as to why...

**Comment by Freddy12** [comment]
I'm working to solve this in my private project as well (my own implementation).

I basically at the same step as you.

If I get any luck will let you know.

**Comment by Mandrakia** [comment]
Great 👍 
So far my steps from current version to where I am : 

- Changed the script parsing (Replaced regex to be more greedy)
- Defined t,k variables in the script
- Defined a dummy getElementById.innerHTML to return the content of the hidden DIV
- Hardcoded a replace of the fill/escape/undefined string with t.charCodeAt(p)
- Made a Java callback for atob to return the decoded b64 string

So far it runs without a crash and generates a code. Problem is, it is not valid apparently.

I must be missing something.

**Comment by Freddy12** [comment]
I did the same steps and also missing something.

It seems that Java scrip engine (V8) is doing something differently than browser.

I did try to compare the answers which I get in Java and browser (giving browser 100% processed javascript script code which I pass to Java script engine).

The browser gives one number, java slightly another (few decimals at the end are off).

Not sure why at the moment.

**Comment by Freddy12** [comment]
Nevermind, the numeric answers seems to be fine (same as in browser), but it still doesn't want to accept it.

**Comment by Freddy12** [comment]
It actually seems to work.

If you're getting 403 status -> it asks you to solve a captcha (after solving it finally gives correct webpage response).

If you're still getting 503 - something is wrong.

I'm still not sure why it asks to solve captcha since via browser there is no need for captcha.

**Comment by Freddy12** [comment]
I have noticed today they have changed the code back to old version.

Probably people were having too much problems with new version.

**Comment by zhkrb** [comment]
It looks like they are rolling back the code. In that code they use eval(t.a.charCodeAt()), so just defendid t (Website domain name)
But I don't know why it wasn't work until now. The answer is the same as the browser , but still not set `cf_clearance`. 

Until the last few minutes ,  it works fine?????
So....sleep on it

**Comment by Freddy12** [comment]
Yeah, I wish I went to sleep earlier yesterday :)))

**Comment by Mandrakia** [comment]
Cloudflare just rolledback the changes, it's back to simple maths operations.

**Comment by tmxd09887** [comment]
Thank you, very useful information

**Comment by Freddy12** [comment]
They again changed it to the more difficult version (with atob and other stuff).

Anyone got it working?

**Comment by zhkrb** [comment]
I have update the code. Now it can pass some test sites,but sometimes still not set the cookie.

Try to use latest version or[ View changes](https://github.com/zhkrb/cloudflare-scrape-Android/commit/e38190cb2ec3c31da90cf735e7ad916dba81cd3c)

**Comment by Freddy12** [comment]
For some sites you after making GET request to that Cloudflare check (with correct answer) -> it gives 403 (not 503) and you just need to solve a Re-Captcha now. After solving the Re-Captcha is finally show the intended web page.

**Comment by zhkrb** [comment]
Yes, you need other code to bypass the Captcha page, try [this](https://github.com/zhkrb/cloudflare-scrape-Android/issues/6#issuecomment-475824285)

**Comment by Freddy12** [comment]
I wonder why they even give that 403 with captcha?

Via browser it never gives me any captcha challenge at all.

It seems like the request from java could still be improved so that they won't give any captcha (like via browser).

**Comment by Mandrakia** [comment]
On the website I use it for, (japscan.to)
I managed to have it working as before, the last error was that the final value isn't answer+(host.length) but just the answer.

**Comment by zhkrb** [comment]
I commented out in the code

**Comment by Mandrakia** [comment]
Working well on android now, last step is my server (.Net) which despite having the same algorithm returns a captcha all the time :/

**Comment by Freddy12** [comment]
Anyone manage to make correct request to Cloudflare so they won't show any captcha? 

Since they don't show any captcha via browser.

**Comment by Mandrakia** [comment]
My version of this project works fine but I tried to refactor it/change some logic a bit and now captcha all the time. I have absolutely no clue as to what triggers the captcha. Answser/Redirect URL is absolutely the same, the timing also.
Only changes are some headers in the redirect call but still no idea what triggers the captcha.

**Comment by bercy46** [comment]
Last comment was in may, what's the status on this ?  I was also using a refactored version of this code on the lowvig.ag web site (I'm not using Android, so basically had to replace TextUtils with StringUtils), and lately I too am always getting a captcha.  Can anyone confirm that the code won't work on that web site ?  Does anyone know of another way to beat Cloudflare ?

**Comment by zhkrb** [comment]
reCAPTCHA is using ip pool to verify user or bot. When an ip visit exceeds a certain range or reCAPTCHA think you are a robot, Cloudflare will return other types verification. You need to handle it yourself

**Comment by bercy46** [comment]
So, are you saying that solving the captcha manually once will unblock it for subsequent bot access, or that my ip address is burnt and I need to get another one ?

**Comment by zhkrb** [comment]
In fact, once you are considered to be problematic by reCAPTCHE, you will get other types verifications back more than once, Using other ip may be effective. And I found that cloudflare changed his code, But I don't have time to update the code now, so you may need to use another repo. sry
